---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: firmware, tags: ['firmware'] }
    - { role: microcode, tags: ['microcode'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: vscode, tags: ['dev'] }
    - { role: google-chrome, tags: ['browser'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: xdg, tags: ['xdg'] }
    - { role: video, tags: ['video'] }
    - { role: media, tags: ['media'] }
    - { role: lightdm, tags: ['lightdm'], when: "display_manager == 'lightdm'" }
    - { role: cinnamon, tags: ['cinnamon'], when: "desktop_environment == 'cinnamon'" }
    - { role: passwords, tags: ['passwords'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: rackspace, tags: ['work'] }
    - { role: firejail, tags: ['firejail'] }
    - { role: unbound, tags: ['unbound'] }
    - { role: editors, tags: ['editors'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: archive, tags: ['archive'] }
