---
- hosts: localhost
  become: yes
  #vars_prompt:
  #  - name: user_password
  #    prompt: "Enter desired user password"
  roles:
    - { role: base, tags: ['base'] }
    - { role: microcode, tags: ['microcode'] }
    - { role: vscode, tags: ['dev'] }
    - { role: google-chrome, tags: ['browser'] }
