---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: cron, tags: ['cron'] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
