---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: ltskernel, tags: ['ltskernel'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: cron, tags: ['cron'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: x, tags: ['x'] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
