---
- hosts: localhost
  become: yes
  #vars_prompt:
  #  - name: user_password
  #    prompt: "Enter desired user password"
  roles:
    - { role: base, tags: ['base'] }
    - { role: firmware, tags: ['firmware'] }
    - { role: microcode, tags: ['microcode'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: vscode, tags: ['dev'] }
    - { role: google-chrome, tags: ['browser'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: xdg, tags: ['xdg'] }
    - { role: video, tags: ['video'] }
