---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: firmware, tags: ['firmware'] }
    - { role: microcode, tags: ['microcode'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: vscode, tags: ['dev'] }
    - { role: google-chrome, tags: ['browser'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: xdg, tags: ['xdg'] }
    - { role: video, tags: ['video'] }
    - { role: media, tags: ['media'] }
    - { role: lightdm, tags: ['lightdm'], when: "display_manager == 'lightdm'" }