---
- name: Install MTR
  pacman:
    name: mtr-gtk

- name: Install iproute2
  pacman:
    name: iproute2

- name: Install bind-tools
  pacman:
    name: bind-tools

- name: Install whois
  pacman:
    name: whois

- name: Install netcat
  pacman:
    name: gnu-netcat

- name: Install sshuttle
  pacman:
    name: sshuttle

- name: Install pdsh
  aur:
    name: pdsh
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install nethogs
  pacman:
    name: nethogs

- name: Install speedtest-cli
  pacman:
    name: speedtest-cli
