---
- name: Install video driver(s)
  pacman:
    name: "{{ video_drivers }}"
  when: video_drivers is defined

- name: Add user to video group
  user:
    name: "{{ user.name }}"
    groups: video
    append: yes
  tags:
    - user
