---
- name: Create /etc/systemd/system.conf.d
  file:
    path: /etc/systemd/system.conf.d
    state: directory

- name: Install VSCode
  aur:
    name: visual-studio-code-bin
    user: "{{ user.name }}"

- name: Check installed extensions
  shell: code --list-extensions
  register: vscode_extensions
  become: yes
  become_user: "{{ user.name }}"

- name: Install VSCode Extensions
  shell: code --install-extension {{ item }}
  loop: "{{ vscode.extensions }}"
  when: item not in vscode_extensions.stdout_lines
  become: yes
  become_user: "{{ user.name }}"
