- name: Install bluetooth libraries and tools
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
      - pulseaudio-bluetooth
      - bluez
      - bluez-libs
      - bluez-utils
      - bluez-firmware
      - blueman
  notify:
    - restart pulse as user

- name: Do not auto power on the bluetooth device
  command: gsettings set org.blueman.plugins.powermanager auto-power-on false
  become: yes
  become_user: "{{ user.name }}"

- name: Unblock the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: no
    state: stopped
  when: bluetooth.disable == False

- name: Enable and start the bluetooth service
  service:
    name: bluetooth.service
    enabled: yes
    state: started
  when: bluetooth.disable == False

- name: Disable and stop the bluetooth service
  service:
    name: bluetooth.service
    enabled: no
    state: stopped
  when: bluetooth.disable == True

- name: Block the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: yes
    state: started
  when: bluetooth.disable == True
