---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install Xinit
  pacman: name=xorg-xinit state=present

- name: Install xmodmap
  pacman: name=xorg-xmodmap state=present

- name: Install xdpyinfo
  pacman: name=xorg-xdpyinfo state=present

- name: Install xev
  pacman: name=xorg-xev state=present

- name: Install xorg-sessreg
  pacman: name=xorg-sessreg state=present

- name: Get GPU manufacturer
  shell: lspci -m | grep VGA | awk -F\" '{printf $4}'
  register: gpu_manufacturer

- name: Get Intel GPU rev
  shell: lspci -m | grep VGA | awk -F\" '{printf substr ($6, 0, 1)}'
  register: intel_gpu_rev
  when: gpu_manufacturer.stdout == "Intel Corporation"

- name: Install video driver(s)
  pacman: name={{ item }} state=present
  with_items: "{{ video_drivers }}"

- name: Install Intel Vulkan driver
  pacman: name=vulkan-intel state=present
  when: gpu_manufacturer.stdout == "Intel Corporation" and intel_gpu_rev.stdout|int >= 6

- name: Add user to video group
  user: name={{ user.name }} groups=video append=yes

# - include: sxhkd.yml # for i3
- include: unclutter.yml
- include: volwheel.yml
# - include: autorandr.yml # for laptop
# - include: srandrd.yml # for laptop
- include: tilix.yml
- include: autocutsel.yml
