---
- name: Install SDDM
  pacman: name=sddm state=present

- name: Install SDDM Theme
  action: aur name={{ item }} user={{ user.name }}
  with_items:
    - wallpaper-archpaint2
    - sddm-theme-archpaint2

- name: Specify SDDM greeter theme
  lineinfile: dest=/etc/sddm.conf
              regexp="^Current="
              state=present
              line="Current=archpaint2"

- name: Enable SDDM
  service: name=sddm.service enabled=yes
