---
- name: Install SDDM
  pacman: name=sddm state=present

- name: Install SDDM Theme
  action: aur name={{ item }} user={{ user.name }}
  with_items:
    - wallpaper-archpaint2
    - sddm-theme-archpaint2

- name: Specify SDDM greeter theme
  lineinfile: dest=/etc/sddm.conf
              regexp="^Current="
              state=present
              line="Current=archpaint2"

- name: Set user profile pic
  get_url: url=https://pbs.twimg.com/profile_images/743307007290028033/IFmFFUwd.jpg
           dest=/home/{{ user.name }}/.face.icon

- name: Enable SDDM
  service: name=sddm.service enabled=yes
