---
- name: Install OpenSSH
  pacman: name=openssh state=present

- name: Push OpenSSH daemon configuration file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config

- name: Create OpenSSH systemd unit file directory
  file: path=/etc/systemd/system/sshd.socket.d state=directory

- name: Push OpenSSH socket unit file
  template: src=sshd-socket-override.conf.j2 dest=/etc/systemd/system/sshd.socket.d/override.conf
  notify:
    - reload systemd config
    - restart sshd

- name: Enable and start OpenSSH server
  service: name=sshd.socket enabled=yes state=started
  when: ssh.enable_sshd == True

- name: Disable and stop OpenSSH server
  service: name=sshd.socket enabled=no state=stopped
  when: ssh.enable_sshd == False

- name: Install sshfs
  pacman: name=sshfs state=present
  when: ssh.sshfs == True

- name: Install autossh
  pacman: name=autossh state=present
  when: ssh.autossh == True

- name: Copy fuse configuration file
  copy: src=fuse.conf dest=/etc/fuse.conf
  when: ssh.sshfs == True

- name: Install keychain
  pacman: name=keychain state=present

- name: Install x11-ask-pass
  pacman: name=x11-ssh-askpass state=present

- name: Export SSH_ASKPASS environment variable
  lineinfile: dest=/etc/profile
              state=present
              line="export SSH_ASKPASS=\"/usr/lib/ssh/x11-ssh-askpass\""

- name: Ensure proper permissions on user SSH dir
  file:
    path: /home/{{ user.name }}/.ssh
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700

- name: Push SSH config
  template:
    src: ssh_config.j2
    dest: /home/{{ user.name }}/.ssh/config
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0600

- name: Make SSH config dir
  file:
    path: /home/{{ user.name }}/.ssh/config.d
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700
  with_fileglob: "config.d/*.conf"

- name: Copy ssh conf files
  copy:
    src: "{{ item }}"
    dest: /home/{{ user.name }}/.ssh/config.d/{{ item | basename }}
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0600
  with_fileglob: "config.d/*.conf"

- name: Make socket dir
  file:
    path: /home/{{ user.name }}/.ssh/sock
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0755

- name: Make directory for user SSH key(s)
  file:
    path: /home/{{ user.name }}/.ssh/keys
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700
  when: ssh.user_keys is defined

- name: Install user SSH key(s)
  copy:
    src: "{{ item }}"
    dest: /home/{{ user.name }}/.ssh/keys/{{ item }}
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0600
  with_items: "{{ ssh.user_keys }}"
  when: ssh.user_keys is defined

- name: Install user public SSH key(s)
  copy:
    src: "{{ item }}.pub"
    dest: /home/{{ user.name }}/.ssh/keys/{{ item }}.pub
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0644
  with_items: "{{ ssh.user_keys }}"
  when: ssh.user_keys is defined

- name: Install Mosh
  pacman: name=mosh state=present
