---
- name: Install OpenSSH
  pacman: name=openssh state=present

- name: Push OpenSSH daemon configuration file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config

- name: Create OpenSSH systemd unit file directory
  file: path=/etc/systemd/system/sshd.socket.d state=directory

- name: Push OpenSSH socket unit file
  template: src=sshd-socket-override.conf.j2 dest=/etc/systemd/system/sshd.socket.d/override.conf
  notify:
    - reload systemd config
    - restart sshd

- name: Enable and start OpenSSH
  service: name=sshd.socket enabled=yes state=started
  when: ssh.enable_sshd == True

- name: Disable and stop OpenSSH
  service: name=sshd.socket enabled=no state=stopped
  when: ssh.enable_sshd == False

- name: Install sshfs
  pacman: name=sshfs state=present

- name: Install autossh
  pacman: name=autossh state=present

- name: Copy fuse configuration file
  copy: src=fuse.conf dest=/etc/fuse.conf

- name: Install keychain
  pacman: name=keychain state=present

- name: Install x11-ask-pass
  pacman: name=x11-ssh-askpass state=present
# Look into using seahorse-ssh-askpass instead

- name: Export SSH_ASKPASS environment variable
  lineinfile: dest=/etc/profile
              state=present
              line="export SSH_ASKPASS=\"/usr/lib/ssh/x11-ssh-askpass\""

- name: Make directory for user SSH key
  file: path=/home/{{ user.name }}/.ssh state=directory mode=700 owner={{ user.name }} group={{ user.group }}

- name: Create user SSH key
  user: name={{ user.name }}
        generate_ssh_key=yes
        ssh_key_type={{ ssh.key_type }}
        ssh_key_bits={{ ssh.key_bits }}
        ssh_key_file=".ssh/id_{{ ssh.key_type }}"
  when: ssh.generate_user_key == True
  tags:
    - user

- name: Install user SSH key
  copy: src={{ ssh.user_key }} dest=/home/{{ user.name }}/.ssh/{{ ssh.user_key.split('/')[-1] }} mode=600 owner={{ user.name }} group={{ user.group }}
  when: ssh.generate_user_key == False and ssh.user_key is defined

- name: Install Mosh
  pacman: name=mosh state=present
