---
- name: Install vagrant
  pacman:
    name: vagrant

- name: Install consul
  pacman:
    name: consul

- name: Install terraform
  pacman:
    name: terraform

- name: Install vault and nomad
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  loop:
    - vault-bin
    - nomad
  tags:
    - aur
