---
- name: Install zip archive utilities
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - zip
    - unzip
    - p7zip
  tags:
    - zip

- name: Install unrar
  pacman:
    name: unrar
    state: present
  tags:
    - unrar

- name: Install optdeps for atool
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - bzip2
    - cpio
    - gzip
    - lha
    - xz
    - lzop
    - tar
    - unace

- name: Install atool
  pacman:
    name: atool
    state: present
  tags:
    - atool

- name: Install hashdeep
  pacman:
    name: hashdeep
    state: present
  tags:
    - hashdeep

- name: Install par2cmdline
  pacman:
    name: par2cmdline
    state: present
  tags:
    - par2

- name: Install ddrescue
  pacman:
    name: ddrescue
    state: present
  tags:
    - ddrescue

- name: Install optdeps for lesspipe
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - rpmextract
    - fastjar
    - cabextract
    - cdrkit
    - html2text
    - antiword
    - unrtf

- name: Install lesspipe
  pacman:
    name: lesspipe
    state: present
  tags:
    - lesspipe
