---
- name: Install zip archive utilities
  pacman:
    name:
      - zip
      - unzip
      - p7zip
  tags:
    - zip

- name: Install unrar
  pacman:
    name: unrar
  tags:
    - unrar

- name: Install optdeps for atool
  pacman:
    name:
      - bzip2
      - cpio
      - gzip
      - lha
      - xz
      - lzop
      - tar
      - unace

- name: Install atool
  pacman:
    name: atool
  tags:
    - atool

- name: Install file-roller
  pacman:
    name: file-roller
  tags:
    - file-roller

- name: Install hashdeep
  pacman:
    name: hashdeep
  tags:
    - hashdeep

- name: Install par2cmdline
  pacman:
    name: par2cmdline
  tags:
    - par2

- name: Install ddrescue
  pacman:
    name: ddrescue
  tags:
    - ddrescue

- name: Install optdeps for lesspipe
  pacman:
    name:
      - rpmextract
      - fastjar
      - cabextract
      - cdrkit
      - html2text
      - antiword
      - unrtf

- name: Install lesspipe
  pacman:
    name: lesspipe
  tags:
    - lesspipe
