---
- name: Install docker
  pacman:
    name: docker

- name: Install docker-compose
  pacman:
    name: docker-compose

- name: Install docker-machine
  pacman:
    name: docker-machine

- name: Create docker group
  group:
    name: docker
    state: present
  tags:
    - user

- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes
  tags:
    - user

- name: Set storage driver for daemon
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Enable and start docker service
  service:
    name: docker.service
    enabled: yes
    state: started