---
- name: Install kernel
  pacman: name={{ item }} state=present
  with_items:
      - linux
      - linux-headers
  notify:
    - rebuild grub

- name: Create systemd-boot loader entries folder
  file: path=/boot/loader/entries state=directory
  when: bootloader == "systemd-boot"

- name: Add kernel bootloader entry
  copy: src=systemd-boot.conf dest=/boot/loader/entries/linux.conf
  when: bootloader == "systemd-boot"
