---
- name: Install sudo
  pacman: name=sudo state=present
  tags:
    - sudo

- name: Add user to wheel group
  user: name={{ user.name }} groups=wheel append=yes
  tags:
    - sudo

- name: Create sudo group
  group: name=sudo state=present

- name: Add user to sudo group
  user: name={{ user.name }} groups=sudo append=yes
  tags:
    - sudo

- name: Copy sudo configuration
  template: src=sudoers.j2 dest=/etc/sudoers mode=440 validate='visudo -cf %s'
  tags:
    - sudo

- name: Create sudoers.d folder
  file: path=/etc/sudoers.d mode=750 state=directory owner=root group=root

- name: Copy sudoers.d configuration
  template: src=sudoers.d.j2
            dest=/etc/sudoers.d/{{ user.name|replace('.', '_') }}
            owner=root group=root mode=440 validate='visudo -cf %s'
  tags:
    - sudo
