---
- name: Create user group
  group: name={{ user.group }} state=present
  tags:
    - user

- name: Create user and assign to group
  user: name={{ user.name }}
        group={{ user.group }}
        password={{ user_password }}
        shell={{ user.shell }}
        update_password=on_create
        uid={{ user.uid }}
  tags:
    - user

- name: Create user log dir
  file: path=/home/{{ user.name }}/{{ user.log_dir }} state=directory owner={{ user.name }} group={{ user.group }}
  when: user.log_dir is defined
  tags:
    - user

- name: Push logrotate config for user logs
  template: src=logrotate.j2 dest=/etc/logrotate.d/user
  when: user.log_dir is defined
  tags:
    - user

- name: Create xdg base dirs and local bin dir
  file: path=/home/{{ user.name }}/{{ item }} state=directory owner={{ user.name }} group={{ user.group }}
  with_items:
    - .config
    - .cache
    - .local/share
    - .local/bin
  when: user.xdg_dirs
  tags:
    - user

- name: Install xdg-user-dirs
  pacman: name=xdg-user-dirs state=present
  when: user.xdg_dirs
  tags:
    - user

- name: Push xdg user dirs config
  copy: src={{ item }} dest=/home/{{ user.name }}/.config/{{ item }} owner={{ user.name }} group={{ user.group }}
  with_items:
    - user-dirs.dirs
    - xdg-dirs.dirs
  when: user.xdg_dirs
  tags:
    - user

- name: Create xdg user dirs
  file: path=/home/{{ user.name }}/{{ item }} state=directory owner={{ user.name }} group={{ user.group }}
  with_items:
    - Desktop
    - Downloads
    - Templates
    - Public
    - Documents
    - Media
    - Media/Music
    - Media/Pictures
    - Media/Videos
