---
# - name: Install alsa-utils
#   pacman:
#     name: alsa-utils

- name: Install PulseAudio
  pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol

- name: Switch output to newly connected devices
  lineinfile:
    dest: /etc/pulse/default.pa
    state: present
    line: "load-module module-switch-on-connect"

- name: Install pasystray
  pacman:
    name: pasystray

- name: Install pulseaudio-ctl
  aur:
    name: pulseaudio-ctl
    user: "{{ user.name }}"
  tags:
    - aur
